my_string = input()
print(my_string.__len__())
print(my_string.upper())
print(my_string.lower())

print(my_string.strip())
my_string = my_string.strip()
print(my_string[:1])
ln = my_string.__len__()
print(my_string[ln -1:])